#!/usr/bin/env bash
#configures nginx on a server and add a custon response header
sudo apt-get update
sudo apt-get install -y nginx

sudo bash -c 'cat > /etc/nginx/conf.d/custom_header.conf <<EOF
add_header X-Served-By \$hostname;
EOF'
sudo service nginx reload

# Stop Nginx service
sudo service nginx stop

# Make nginx files readable and writable
sudo chmod 7704 /etc/nginx/*



# Test the config
sudo nginx -t

# Restart Nginx service
sudo service nginx start
