#!/usr/bin/env bash
# Tells a story based on the contents of /etc/passwd

while IFS=':' read -r username password uid gid info home shell; do
	echo "The user $username is part of the $gid gang;"\
		"lives in $home and rides $shell."\
		"$uid's place is protected by the passcode $password,"\
		"more info about user here: $info"
	done < "/etc/passwd"
