#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	fi
	echo "Best School"
	(( count++ ))
done
